name: flutrlint
description: A custom analysis_options.yaml file for Flutter Turkey organization projects.
version: 1.0.0
publish_to: "none"
homepage: https://github.com/flutterturkey/flutrlint
repository: https://github.com/flutterturkey/flutrlint
issue_tracker: https://github.com/flutterturkey/flutrlint/issues

environment:
  sdk: ">=2.7.0 <3.0.0"
