name: flutrlint
description: A custom analysis_options.yaml file created from Flutter Turkey for organization projects and anyone else.
version: 3.0.0
homepage: https://github.com/flutterturkey/flutrlint
repository: https://github.com/flutterturkey/flutrlint
issue_tracker: https://github.com/flutterturkey/flutrlint/issues

environment:
  sdk: ">=2.17.0 <3.0.0"
